name: Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Train models
      run: |
        python ml_model.py
    - name: Deploy to Streamlit
      env:
        STREAMLIT_APP_TOKEN: ${{ secrets.STREAMLIT_APP_TOKEN }}
      run: |
        streamlit run app.py